### ISSUE TITLE
Fails to build if AVX2 is enabled by default

### ISSUE THREAD

**Issue by jbeich** [hsivonen/simd#24]
```rust
$ RUSTC_BOOTSTRAP=1 RUSTFLAGS="-C target-feature=+avx2" cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling simd v0.2.1 (file:///tmp/simd)
error[E0442]: intrinsic return value has wrong type: found vector with length 4, expected length 32
  --> src/x86/avx2.rs:45:5
   |
45 |     fn x86_mm256_sad_epu8(x: u8x32, y: u8x32) -> u64x4;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
error: Could not compile `simd`.
```
Regressed by cf87865a998a, see also [Mozilla bug 1433747](https://bugzilla.mozilla.org/show_bug.cgi?id=1433747)

**Comment by BurntSushi** [comment]
This isn't a regression? This crate tracks the latest nightly. cf87865 was an update to make this crate work on the latest nightly.

**Comment by jbeich** [comment]
I confirm, Nightly 1.25 and Beta 1.24 aren't affected.
